# Generated by Django 3.0.8 on 2021-09-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='post',
        ),
    ]
